export const DOCUMENT_TYPES = {
  fair_housing_policy: {
    label: 'Fair Housing Policy',
    category: 'federal' as const,
    description: 'Federal Fair Housing Act compliance policy',
  },
  lead_disclosure: {
    label: 'Lead-Based Paint Disclosure',
    category: 'federal' as const,
    description: 'EPA/HUD lead-based paint disclosure for pre-1978 properties',
  },
  emergency_action_plan: {
    label: 'Emergency Action Plan',
    category: 'federal' as const,
    description: 'OSHA-compliant Emergency Action Plan',
  },
  ada_policy: {
    label: 'ADA Compliance Policy',
    category: 'federal' as const,
    description: 'Americans with Disabilities Act compliance policy',
  },
  landlord_tenant_rights: {
    label: 'Landlord-Tenant Rights Disclosure',
    category: 'state' as const,
    description: 'State-specific landlord-tenant law disclosure',
  },
  phila_rental_license: {
    label: 'Rental License Compliance Checklist',
    category: 'local' as const,
    description: 'Philadelphia rental license and inspection requirements',
  },
  phila_lead_safe: {
    label: 'Lead Safe Certification Compliance',
    category: 'local' as const,
    description: 'Philadelphia lead-safe certification requirements',
  },
} as const;

export type DocumentType = keyof typeof DOCUMENT_TYPES;

export const JURISDICTIONS = {
  federal: { label: 'Federal', type: 'federal' },
  PA: { label: 'Pennsylvania', type: 'state' },
  Philadelphia_PA: { label: 'Philadelphia, PA', type: 'local' },
} as const;

export type Jurisdiction = keyof typeof JURISDICTIONS;

export const PROPERTY_TYPES = {
  residential_multifamily: 'Residential - Multifamily',
  residential_single: 'Residential - Single Family',
  commercial: 'Commercial',
  mixed_use: 'Mixed Use',
} as const;

export const SUBSCRIPTION_PLANS = {
  starter: {
    name: 'Starter',
    price: 147,
    priceId: process.env.STRIPE_PRICE_ID_STARTER || '',
    features: [
      'Up to 5 properties',
      '10 document drafts/month',
      'Federal + 1 state jurisdiction',
      'Email alerts',
      'PDF export',
    ],
    limits: {
      properties: 5,
      documentsPerMonth: 10,
      jurisdictions: 2,
    },
  },
  professional: {
    name: 'Professional',
    price: 297,
    priceId: process.env.STRIPE_PRICE_ID_PROFESSIONAL || '',
    features: [
      'Up to 25 properties',
      'Unlimited document drafts',
      'Federal + all states + local',
      'Priority alerts',
      'PDF export',
      'Team access (up to 5)',
    ],
    limits: {
      properties: 25,
      documentsPerMonth: Infinity,
      jurisdictions: Infinity,
    },
  },
  enterprise: {
    name: 'Enterprise',
    price: 597,
    priceId: process.env.STRIPE_PRICE_ID_ENTERPRISE || '',
    features: [
      'Unlimited properties',
      'Unlimited document drafts',
      'All jurisdictions',
      'White-label option',
      'API access',
      'Dedicated support',
      'Unlimited team members',
    ],
    limits: {
      properties: Infinity,
      documentsPerMonth: Infinity,
      jurisdictions: Infinity,
    },
  },
} as const;

export type SubscriptionPlan = keyof typeof SUBSCRIPTION_PLANS;

export const STATUS_COLORS = {
  current: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', dot: 'bg-emerald-500' },
  draft: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', dot: 'bg-blue-500' },
  needs_review: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', dot: 'bg-amber-500' },
  outdated: { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200', dot: 'bg-red-500' },
} as const;

export const STATUS_LABELS: Record<string, string> = {
  current: 'Current Draft',
  draft: 'New Draft',
  needs_review: 'Needs Review',
  outdated: 'Outdated',
};

export const SEVERITY_COLORS = {
  critical: { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
  warning: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  info: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
} as const;

export const ENTITY_TYPES = [
  'LLC',
  'Corporation',
  'S-Corporation',
  'Limited Partnership',
  'Sole Proprietorship',
  'Non-Profit',
  'Other',
] as const;

export const US_STATES = [
  { code: 'PA', name: 'Pennsylvania' },
] as const;

export const LEGAL_DISCLAIMER = `DRAFT — REVIEW WITH QUALIFIED COUNSEL BEFORE IMPLEMENTATION

This document TEMPLATE was generated by RegLynx based on published
federal, state, and local regulations as of the generation date.
This is NOT legal advice. RegLynx is not a law firm and does not
provide legal services. This template is a starting point that MUST
be reviewed and approved by qualified legal counsel before use in
your operations. RegLynx makes no warranty regarding the completeness
or accuracy of regulatory information. Use of this template is at
your own risk.

RegLynx | reglynx.com | support@reglynx.com
Ramesses Management & Contracting LLC | Philadelphia, PA`;

export const FOOTER_LEGAL_LINE =
  'RegLynx is not a law firm and does not provide legal advice. All generated document templates should be reviewed by qualified counsel before implementation.';
